apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: windows-block-sc
