apiVersion: v1
kind: Pod
metadata:
  name: windows-example-pod
spec:
  nodeSelector:
    kubernetes.io/os: windows
  containers:
    - name: test-container
      image: mcr.microsoft.com/powershell:nanoserver-1809
      command:
        - pwsh
      args:
        - -command
        - while ($true) { sleep 10 }
        - echo 'hello' > /mnt/volume1
      volumeMounts:
        - name: test-volume
          mountPath: /mnt/volume1
  restartPolicy: Never
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: windows-example-pvc
